FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --production

COPY . .

# Sets the internal port environment variable automatically
ENV PORT=3004

EXPOSE 3004

CMD ["node", "index.js"]