mongodb.uri=mongodb://cvdiaz3_db_user:admin123@ac-b9fz9za-shard-00-00.vigvruj.mongodb.net:27017,ac-b9fz9za-shard-00-01.vigvruj.mongodb.net:27017,ac-b9fz9za-shard-00-02.vigvruj.mongodb.net:27017/?ssl=true&replicaSet=atlas-800eio-shard-0&authSource=admin&appName=Cluster0
mongodb.database=productWeight
mongodb.collection=registerProduct

spring.application.name=ProductManager
server.port=8080
