-- American Latin Class - esquema base para Supabase
-- Uso: Supabase Dashboard > SQL Editor > New query > pegar y ejecutar.
-- Nota: estas politicas anonimas son para mockup academico.
-- En produccion se debe usar Supabase Auth y permisos por rol/sede.

create table if not exists public.sedes (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  color text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.alumnos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  sede text not null references public.sedes(nombre),
  clase_nivel text not null,
  estado text not null check (estado in ('Activo', 'Inactivo')),
  beca_convenio text not null check (beca_convenio in ('No aplica', 'Beca', 'Convenio')),
  telefono text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.mensualidades (
  id bigint generated by default as identity primary key,
  alumno text not null,
  sede text not null references public.sedes(nombre),
  periodo text not null,
  monto numeric(10, 2) not null check (monto >= 0),
  estado_pago text not null check (estado_pago in ('Al dia', 'Atrasado', 'Becado/Convenio')),
  recibo text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.asistencias (
  id bigint generated by default as identity primary key,
  fecha date not null,
  sede text not null references public.sedes(nombre),
  clase text not null,
  profesor text not null,
  alumno text not null,
  estado text not null check (estado in ('Presente', 'Ausente', 'Tarde', 'Justificado')),
  evidencia text not null,
  created_at timestamptz not null default now()
);

insert into public.sedes (nombre, color)
values
  ('Matriz', 'Amarillo'),
  ('Norte', 'Azul'),
  ('Quitumbe', 'Naranja'),
  ('Tumbaco', 'Morado'),
  ('Conocoto', 'Rosado')
on conflict (nombre) do nothing;

insert into public.alumnos (nombre, sede, clase_nivel, estado, beca_convenio, telefono)
select 'Camila Rojas', 'Matriz', 'Salsa inicial', 'Activo', 'No aplica', '099 148 2301'
where not exists (select 1 from public.alumnos);

insert into public.alumnos (nombre, sede, clase_nivel, estado, beca_convenio, telefono)
select 'Mateo Vera', 'Norte', 'Bachata 2', 'Activo', 'Convenio', '098 441 0210'
where not exists (select 1 from public.alumnos where nombre = 'Mateo Vera');

insert into public.alumnos (nombre, sede, clase_nivel, estado, beca_convenio, telefono)
select 'Valeria Paz', 'Quitumbe', 'Urbano teens', 'Activo', 'Beca', '097 220 4402'
where not exists (select 1 from public.alumnos where nombre = 'Valeria Paz');

insert into public.mensualidades (alumno, sede, periodo, monto, estado_pago, recibo)
select 'Camila Rojas', 'Matriz', '2026-04', 45, 'Al dia', 'REC-001'
where not exists (select 1 from public.mensualidades);

insert into public.mensualidades (alumno, sede, periodo, monto, estado_pago, recibo)
select 'Mateo Vera', 'Norte', '2026-04', 45, 'Atrasado', 'REC-002'
where not exists (select 1 from public.mensualidades where recibo = 'REC-002');

insert into public.mensualidades (alumno, sede, periodo, monto, estado_pago, recibo)
select 'Valeria Paz', 'Quitumbe', '2026-04', 0, 'Becado/Convenio', 'REC-003'
where not exists (select 1 from public.mensualidades where recibo = 'REC-003');

insert into public.asistencias (fecha, sede, clase, profesor, alumno, estado, evidencia)
select '2026-04-20', 'Tumbaco', 'Bachata inicial', 'Andrea Molina', 'Daniela Arias', 'Presente', 'QR-ALC-1201'
where not exists (select 1 from public.asistencias);

insert into public.asistencias (fecha, sede, clase, profesor, alumno, estado, evidencia)
select '2026-04-20', 'Conocoto', 'Salsa intermedio', 'Marco Diaz', 'Julian Mena', 'Ausente', 'QR-ALC-1202'
where not exists (select 1 from public.asistencias where evidencia = 'QR-ALC-1202');

alter table public.sedes enable row level security;
alter table public.alumnos enable row level security;
alter table public.mensualidades enable row level security;
alter table public.asistencias enable row level security;

drop policy if exists "Lectura publica sedes" on public.sedes;
drop policy if exists "Lectura publica alumnos" on public.alumnos;
drop policy if exists "Insercion publica alumnos" on public.alumnos;
drop policy if exists "Lectura publica mensualidades" on public.mensualidades;
drop policy if exists "Insercion publica mensualidades" on public.mensualidades;
drop policy if exists "Lectura publica asistencias" on public.asistencias;
drop policy if exists "Insercion publica asistencias" on public.asistencias;

create policy "Lectura publica sedes"
on public.sedes for select
to anon
using (true);

create policy "Lectura publica alumnos"
on public.alumnos for select
to anon
using (true);

create policy "Insercion publica alumnos"
on public.alumnos for insert
to anon
with check (true);

create policy "Lectura publica mensualidades"
on public.mensualidades for select
to anon
using (true);

create policy "Insercion publica mensualidades"
on public.mensualidades for insert
to anon
with check (true);

create policy "Lectura publica asistencias"
on public.asistencias for select
to anon
using (true);

create policy "Insercion publica asistencias"
on public.asistencias for insert
to anon
with check (true);
