services:
  - type: web
    name: formweb-estudiante
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGODB_URI
        sync: false   # Lo defines manualmente en el dashboard de Render
