-- American Latin Class - Supabase schema for HW06 ORM and PHP.
-- This version separates public enrollment, real login, role permissions, and the student attendance kiosk.

create table if not exists public.branches (
  id bigint generated by default as identity primary key,
  name text not null unique,
  director_name text not null,
  co_director_name text,
  matrix_share_percent numeric(5,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  national_id text,
  full_name text not null,
  email text not null,
  phone text not null,
  level text not null check (level in ('B1', 'B2')),
  scholarship_percent integer not null default 0 check (scholarship_percent in (0, 50, 75, 100)),
  guardian_name text,
  guardian_phone text,
  status text not null default 'pending' check (status in ('pending', 'active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.students add column if not exists national_id text;

create unique index if not exists students_national_id_unique
  on public.students (national_id)
  where national_id is not null and national_id <> '';

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  role text not null check (role in ('teacher', 'student', 'director')),
  name text not null,
  branch_id bigint references public.branches(id),
  student_id bigint references public.students(id),
  is_active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.class_plans (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  teacher_name text not null,
  month text not null,
  level text not null check (level in ('B1', 'B2')),
  objective text not null,
  activities text not null,
  status text not null default 'submitted' check (status in ('submitted', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  student_id bigint references public.students(id),
  national_id text,
  person_type text not null check (person_type in ('student', 'teacher')),
  person_name text not null,
  level text,
  attendance_date date not null,
  check_in_at timestamptz,
  status text not null check (status in ('present', 'absent', 'late', 'excused')),
  source text not null default 'manual' check (source in ('manual', 'kiosk')),
  evidence_code text not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.attendance_records add column if not exists student_id bigint references public.students(id);
alter table public.attendance_records add column if not exists national_id text;
alter table public.attendance_records add column if not exists level text;
alter table public.attendance_records add column if not exists check_in_at timestamptz;
alter table public.attendance_records add column if not exists source text not null default 'manual';

create table if not exists public.branch_finance_reports (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  month text not null,
  income numeric(10,2) not null default 0,
  expenses numeric(10,2) not null default 0,
  matrix_share_percent numeric(5,2) not null default 0,
  matrix_share_amount numeric(10,2) not null default 0,
  net_result numeric(10,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.branch_finance_reports add column if not exists matrix_share_amount numeric(10,2) not null default 0;
alter table public.branch_finance_reports add column if not exists net_result numeric(10,2) not null default 0;

create table if not exists public.professional_events (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  client_name text not null,
  event_type text not null,
  event_date date not null,
  total_amount numeric(10,2) not null default 0,
  status text not null default 'pending_payment' check (status in ('pending_payment', 'paid', 'settled', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dancer_event_assignments (
  id bigint generated by default as identity primary key,
  professional_event_id bigint not null references public.professional_events(id),
  student_id bigint not null references public.students(id),
  gross_amount numeric(10,2) not null default 0,
  deduction_amount numeric(10,2) not null default 0,
  deduction_reason text,
  payment_status text not null default 'pending' check (payment_status in ('pending', 'paid')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.branches (name, director_name, co_director_name, matrix_share_percent)
values
  ('Matriz', 'Juan Pablo Hidalgo', 'Pending validation', 0),
  ('Norte', 'Pending validation', 'Pending validation', 15),
  ('Quitumbe', 'Pending validation', 'Pending validation', 15),
  ('Conocoto', 'Pending validation', 'Pending validation', 15),
  ('Tumbaco', 'Pending validation', 'Pending validation', 15)
on conflict (name) do nothing;

insert into public.students (branch_id, national_id, full_name, email, phone, level, scholarship_percent, guardian_name, guardian_phone, status)
select 3, '1723456789', 'Valeria Paz', 'alumno@americanlatinclass.com', '0990000000', 'B2', 100, 'Luis Paz', '0991112222', 'active'
where not exists (select 1 from public.students where national_id = '1723456789');

insert into public.students (branch_id, national_id, full_name, email, phone, level, scholarship_percent, guardian_name, guardian_phone, status)
select 2, '1712345678', 'Mateo Vera', 'mateo.vera@correo.com', '0982223333', 'B1', 50, 'Patricia Vera', '0983334444', 'active'
where not exists (select 1 from public.students where national_id = '1712345678');

insert into public.students (branch_id, national_id, full_name, email, phone, level, scholarship_percent, guardian_name, guardian_phone, status)
select 4, '1709876543', 'Julian Mena', 'julian.mena@correo.com', '0975556666', 'B2', 75, 'Andrea Mena', '0976667777', 'active'
where not exists (select 1 from public.students where national_id = '1709876543');

insert into public.users (email, password_hash, role, name, branch_id, student_id, is_active)
values
  ('profesor@americanlatinclass.com', '$2b$10$0VNCWCIY.SlWyOMfPJ2SvuJwRBpt31UKs5GyIHj2cFnfVKQC1RSi6', 'teacher', 'Andrea Molina', 1, null, true),
  ('director@americanlatinclass.com', '$2b$10$0VNCWCIY.SlWyOMfPJ2SvuJwRBpt31UKs5GyIHj2cFnfVKQC1RSi6', 'director', 'Juan Pablo Hidalgo', 1, null, true),
  ('alumno@americanlatinclass.com', '$2b$10$0VNCWCIY.SlWyOMfPJ2SvuJwRBpt31UKs5GyIHj2cFnfVKQC1RSi6', 'student', 'Valeria Paz', 3, (select id from public.students where national_id = '1723456789'), true)
on conflict (email) do update set
  password_hash = excluded.password_hash,
  role = excluded.role,
  name = excluded.name,
  branch_id = excluded.branch_id,
  student_id = excluded.student_id,
  is_active = excluded.is_active,
  updated_at = now();

insert into public.attendance_records (branch_id, student_id, national_id, person_type, person_name, level, attendance_date, check_in_at, status, source, evidence_code, notes)
select 3, s.id, s.national_id, 'student', s.full_name, s.level, current_date, now(), 'present', 'kiosk', 'ALC-SEED-0001', 'Seed attendance for monthly student view.'
from public.students s
where s.national_id = '1723456789'
  and not exists (
    select 1 from public.attendance_records ar
    where ar.student_id = s.id and ar.attendance_date = current_date
  );

alter table public.branches enable row level security;
alter table public.students enable row level security;
alter table public.users enable row level security;
alter table public.class_plans enable row level security;
alter table public.attendance_records enable row level security;
alter table public.branch_finance_reports enable row level security;
alter table public.professional_events enable row level security;
alter table public.dancer_event_assignments enable row level security;

drop policy if exists "Academic read branches" on public.branches;
drop policy if exists "Academic insert students" on public.students;
drop policy if exists "Academic read students" on public.students;
drop policy if exists "Academic insert class plans" on public.class_plans;
drop policy if exists "Academic insert attendance records" on public.attendance_records;
drop policy if exists "Academic read branch finance reports" on public.branch_finance_reports;
drop policy if exists "Academic insert branch finance reports" on public.branch_finance_reports;
drop policy if exists "Academic read professional events" on public.professional_events;
drop policy if exists "Academic insert professional events" on public.professional_events;
drop policy if exists "Academic read dancer assignments" on public.dancer_event_assignments;
drop policy if exists "Academic public read branches" on public.branches;

create policy "Academic public read branches" on public.branches for select to anon using (true);
