service: fabula-dental-patients

provider:
  name: aws
  runtime: python3.11
  region: us-east-2
  environment:
    DATABASE_URL: "postgresql://postgres.hoskmelosabzuxjvbjyk:fabuladental30716@aws-1-us-east-2.pooler.supabase.com:5432/postgres"
    DIRECT_URL: "postgresql://postgres.hoskmelosabzuxjvbjyk:fabuladental30716@aws-1-us-east-2.pooler.supabase.com:5432/postgres"
    CRUD_API_KEY: "admin"
    JWT_SECRET: "fabuladental_jwt_super_secreto_2024"

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: false
    bin: "C:\\Users\\USER\\.cache\\codex-runtimes\\codex-primary-runtime\\dependencies\\python\\python.exe"