-- American Latin Class - Supabase schema for the HW08 frontend.
-- This schema matches the names used by script/app.js and script/supabase-client.js.

create table if not exists public.branches (
  id bigint generated by default as identity primary key,
  name text not null unique,
  director_name text not null,
  co_director_name text,
  matrix_share_percent numeric(5,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  full_name text not null,
  email text not null,
  phone text not null,
  level text not null check (level in ('B1', 'B2')),
  scholarship_percent integer not null default 0 check (scholarship_percent in (0, 50, 75, 100)),
  guardian_name text,
  guardian_phone text,
  status text not null default 'pending' check (status in ('pending', 'active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.class_plans (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  teacher_name text not null,
  month text not null,
  level text not null check (level in ('B1', 'B2')),
  objective text not null,
  activities text not null,
  status text not null default 'submitted' check (status in ('submitted', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  person_type text not null check (person_type in ('student', 'teacher')),
  person_name text not null,
  attendance_date date not null,
  status text not null check (status in ('present', 'absent', 'late', 'excused')),
  evidence_code text not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.branch_finance_reports (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  month text not null,
  income numeric(10,2) not null default 0,
  expenses numeric(10,2) not null default 0,
  matrix_share_percent numeric(5,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.professional_events (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  client_name text not null,
  event_type text not null,
  event_date date not null,
  total_amount numeric(10,2) not null default 0,
  status text not null default 'pending_payment' check (status in ('pending_payment', 'paid', 'settled', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.branches (name, director_name, co_director_name, matrix_share_percent)
values
  ('Matriz', 'Juan Pablo Hidalgo', 'Pending validation', 0),
  ('Norte', 'Pending validation', 'Pending validation', 15),
  ('Quitumbe', 'Pending validation', 'Pending validation', 15),
  ('Conocoto', 'Pending validation', 'Pending validation', 15),
  ('Tumbaco', 'Pending validation', 'Pending validation', 15)
on conflict (name) do nothing;

alter table public.branches enable row level security;
alter table public.students enable row level security;
alter table public.class_plans enable row level security;
alter table public.attendance_records enable row level security;
alter table public.branch_finance_reports enable row level security;
alter table public.professional_events enable row level security;

drop policy if exists "HW08 read branches" on public.branches;
drop policy if exists "HW08 read students" on public.students;
drop policy if exists "HW08 insert students" on public.students;
drop policy if exists "HW08 insert class plans" on public.class_plans;
drop policy if exists "HW08 insert attendance records" on public.attendance_records;
drop policy if exists "HW08 insert finance reports" on public.branch_finance_reports;
drop policy if exists "HW08 read professional events" on public.professional_events;
drop policy if exists "HW08 insert professional events" on public.professional_events;

create policy "HW08 read branches" on public.branches for select to anon using (true);
create policy "HW08 read students" on public.students for select to anon using (true);
create policy "HW08 insert students" on public.students for insert to anon with check (true);
create policy "HW08 insert class plans" on public.class_plans for insert to anon with check (true);
create policy "HW08 insert attendance records" on public.attendance_records for insert to anon with check (true);
create policy "HW08 insert finance reports" on public.branch_finance_reports for insert to anon with check (true);
create policy "HW08 read professional events" on public.professional_events for select to anon using (true);
create policy "HW08 insert professional events" on public.professional_events for insert to anon with check (true);

